### PR TITLE
Adds support for java 11.

### PR DESCRIPTION
**Pull request by damencho**

### CODE REVIEW

**Comment by JonathanLennox** [comment]
I think the dependency changes should be covered by https://github.com/jitsi/jibri/pull/251, since it's Jersey that needs them?

What needed the maven-compiler-plugin change?

**Comment by damencho** [comment]
> What needed the maven-compiler-plugin change?

I need to find it, but this was recommended for java11 support.

**Comment by damencho** [comment]
Like this one: https://winterbe.com/posts/2018/08/29/migrate-maven-projects-to-java-11-jigsaw/#configure-plugins-for-java-11

**Comment by JonathanLennox** [comment]
Looks like that advice is for _building_ with java11, not _running_ with it; that said, see https://github.com/jitsi/jibri/pull/252 .

**Comment by damencho** [comment]
Thanks.

**Pull request closed without merging**
