### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tes5884**
Fixed formatting, and removed sections referring to old python packages. Especially since debian packages are the new go too.

I haven't done many PR's before, If I'm doing something wrong, please tell me.

### CODE REVIEW

**Comment by tes5884** [comment]
Did the CLA

**Comment by bbaldino** [comment]
@tes5884 can you rebase this?  there are some conflicts with @aaronkvanmeerten 's readme change

**Comment by tes5884** [comment]
Sure, let me figure out how to do that first ;-)

**Comment by tes5884** [comment]
I rebased my PR. Not sure if it updated here (I'm a bona fide newb).. Does it look ok to you?

**Comment by bbaldino** [comment]
rebase looks good...i'll leave it to @aaronkvanmeerten to approve and merge the changes.  thanks @tes5884 !

**Pull request merged**
