### PR TITLE
update Config files

### PR DESCRIPTION
**Pull request by daxiondi**
Thanks to the jitsi team for providing jibri.
- I tested this installation tutorial for both Ubuntu 16.04 and Ubuntu 18.04.
- After executing `apt -y install linux-image-extra-virtual`,  I need to perform `reboot`.
- Many community questions are not clearly written in the `config files`, so this is supplemented.
- If there are multiple Java environments, such as Java 11, there will be problems with the startup. Therefore, install java8 in the document and start it with java8.

### CODE REVIEW

**Comment by daxiondi** [comment]
@saghul Please review the code for me，In addition, do you have any good suggestions for [my questions](https://community.jitsi.org/t/discussion-on-using-multiple-jibri-to-record-multiple-videos-at-the-same-time/71510) in the forum?

**Comment by bbaldino** [comment]
Have you tried running tip of master with Java 11?  I made some changes recently which I thought might fix it, but I only had time to test compilation, not running.

**Comment by daxiondi** [comment]
I started jibri recording successfully using java 11, but the following error occurred in the [log](https://gist.github.com/daxiondi/6e864f35219410ad7b0afe4acd1e9c77).
I use `AdoptOpenJDK version 11.0.8`.
If you think this is OK, I will delete the description of Java 11 in PR.

**Comment by bbaldino** [comment]
> I started jibri recording successfully using java 11, but the following error occurred in the [log](https://gist.github.com/daxiondi/6e864f35219410ad7b0afe4acd1e9c77).
> I use `AdoptOpenJDK version 11.0.8`.
> If you think this is OK, I will delete the description of Java 11 in PR.

What Jibri version of that? The (potential) java 11 fixes are pretty recent.

**Comment by daxiondi** [comment]
I added `Jitsi repository`, installed it with `apt intsall jibri` and executed `dpkg - L | grep jibri`. It outputs `8.0-14-g0ccc3f6-1`.

Does this version support java11?

Or is there any other way to view the jibri version?

Do you think my PR about `install Java` needs to be adjusted?

**Comment by bbaldino** [comment]
No, you want `jibri_8.0-34-gd133175-1`, I just promoted it to stable the other day.

**Comment by daxiondi** [comment]
ok。 So please review my PR.
can you answer my distress in the [forum](https://community.jitsi.org/t/discussion-on-using-multiple-jibri-to-record-multiple-videos-at-the-same-time/71510)?

**Comment by daxiondi** [comment]
@bbaldino Do you have time to review? Look forward to your reply.

**Comment by daxiondi** [comment]
@bbaldino hi, if this pr is not needed.
I will close it, because it has been waiting for a while, looking forward to your reply

**Comment by bbaldino** [comment]
I was hoping you could re check running with Java 11 to see if that worked before adding to the doc that it doesn't

**Comment by daxiondi** [comment]
> I started jibri recording successfully using java 11, but the following error occurred in the [log](https://gist.github.com/daxiondi/6e864f35219410ad7b0afe4acd1e9c77).
> I use `AdoptOpenJDK version 11.0.8`.
> If you think this is OK, I will delete the description of Java 11 in PR.

I re-use Java11 to run Jibri and still get the same error, please see the quote above, 
so I think Java11 is not the best choice to run Jibri at present, 
so we can remind everyone that it is best to use Java8

**Comment by bbaldino** [comment]
> > I started jibri recording successfully using java 11, but the following error occurred in the [log](https://gist.github.com/daxiondi/6e864f35219410ad7b0afe4acd1e9c77).
> > I use `AdoptOpenJDK version 11.0.8`.
> > If you think this is OK, I will delete the description of Java 11 in PR.
> 
> I re-use Java11 to run Jibri and still get the same error, please see the quote above,
> so I think Java11 is not the best choice to run Jibri at present,
> so we can remind everyone that it is best to use Java8

Did you re-try it on jibri_8.0-34-gd133175-1 ?

**Comment by daxiondi** [comment]
Do you need me to uninstall version `8.0-14-g0ccc3f6-1` to use version `jibri_8.0-34-gd133175-1`?
How to install `jibri_8.0-34-gd133175-1`
Add source, `apt-get update`, `apt-get install jibri`?

**Comment by bbaldino** [comment]
> Do you need me to uninstall version `8.0-14-g0ccc3f6-1` to use version `jibri_8.0-34-gd133175-1`?
> How to install `jibri_8.0-34-gd133175-1`
> Add source, `apt-get update`, `apt-get install jibri`?

I think upgrade should work.  The deb is [here](https://download.jitsi.org/stable/jibri_8.0-34-gd133175-1_all.deb) if you want to grab it directly.

**Comment by daxiondi** [comment]
@bbaldino 
I reinstalled Jibri, and the current version is `8.0-34-gd133175-1`.
I got the same [error](https://gist.github.com/daxiondi/6e864f35219410ad7b0afe4acd1e9c77) last time when using Java11, 
please check here, so I think `8.0-34-gd133175-1` does not support Java11 very well, 
so It is necessary to tell the user that the Java 8 environment is required

**Comment by bbaldino** [comment]
> @bbaldino
> I reinstalled Jibri, and the current version is `8.0-34-gd133175-1`.
> I got the same [error](https://gist.github.com/daxiondi/6e864f35219410ad7b0afe4acd1e9c77) last time when using Java11,
> please check here, so I think `8.0-34-gd133175-1` does not support Java11 very well,
> so It is necessary to tell the user that the Java 8 environment is required

Are you sure you're on 8.0-34? That error is from jersey and 8.0-34 isn't using jersey anymore.

**Comment by daxiondi** [comment]
I installed it on a new machine with only one jibri version. The following is a screenshot.
image
image

**Comment by daxiondi** [comment]
@bbaldino I think you can practice it manually to know if the problem I said really exists

**Pull request closed without merging**
